version: '3.9'
services:
  my-fastapi-service:
    container_name: whos-my-ta
    build:
      context: .
      dockerfile: Dockerfile
    image: rec_image:latest
    ports:
      - "4567:4567"
    cpus: 1
    mem_limit: 1024m
